myform/forms/urls.py
from django.urls import path
from . import views

app_name='forms'
urlpatterns = [
    path('', views.entry, name='entry'),
    path('confirm/', views.confirm, name='confirm'),
    path('complete/', views.complete, name='complete'),
]

myform/myform/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('forms/', include('forms.urls')),
    path('admin/', admin.site.urls),
]

myform/forms/models.py
from django.db import models

# Create your models here.

class Entry(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=100)

    def __str__(self):
        return self.name

myform/forms/admin.py
from django.contrib import admin
from forms.models import Entry

# Register your models here.
#from .models import Entry

#admin.site.register(Entry)

class EntryAdmin(admin.ModelAdmin):
    list_display = ('id','name', 'address',)
#    list_display_links = ('id',)
admin.site.register(Entry, EntryAdmin)

myform/forms/apps.py
from django.apps import AppConfig


class FormsConfig(AppConfig):
    name = 'forms'

myform/forms/forms.py
from django.forms import ModelForm
from forms.models import Entry

class EntryForm(ModelForm):
    class Meta:
        model = Entry
        fields = ('name', 'address',)

myform/forms/tests.py
from django.test import TestCase

# Create your tests here.

myform/forms/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.views.decorators.http import require_POST

from forms.models import Entry
from forms.forms import EntryForm

# Create your views here.
def entry(request):

    form = EntryForm(request.POST or None)
    context = {'form': form,}

    return render(request, 'forms/entry.html', context)


def confirm(request):
    form = EntryForm(request.POST)
    context = {'form': form,}

    if form.is_valid():
        return render(request, 'forms/confirm.html', context)

    return render(request, 'forms/entry.html', context)


def complete(request):

    if request.method == 'POST':
        form = EntryForm(request.POST)
        if form.is_valid():
            entry = form.save(commit=False)
            entry.save()
            return redirect('forms:complete')
    else:
        form = EntryForm()
    
    return render(request, 'forms/complete.html', {'form': form})

myform/forms/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}">
<head>
<meta charset="UTF-8">
<title>{% block title %}My Forms{% endblock %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/bootstrap-theme.min.css' %}" rel="stylesheet">
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block extrahead %}{% endblock %}
</head>
<body>
  <div class="container">
    {% block content %}
      {{ content }}
    {% endblock %}
  </div>
</body>
</html>

myform/forms/templates/forms/complete.html
{% block content %}
登録できました！<br>

<a href=../>TOPへ</a>
{% endblock %}

myform/forms/templates/forms/confirm.html
{% extends "base.html" %}
{% load bootstrap %}

{% block title %}確認{% endblock title %}

{% block content %}
    <h3 class="page-header">確認</h3>
    {% for field in form %}
        {{ field.label_tag }}{{ field.value }}<br>
    {% endfor %}
    <form action="{% url 'forms:complete' %}" method="post" class="form-horizontal" role="form">
        <div style="display:none">
            {% csrf_token %}
            {{ form|bootstrap_horizontal }}
        </div>
        <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-primary">応募</button>
                </div>
        </div>
    </form>

    <form action="{% url 'forms:entry' %}" method="post" class="form-horizontal" role="form">
        <div style="display:none">
            {% csrf_token %}
            {{ form|bootstrap_horizontal }}
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">戻る</button>
            </div>
        </div>
  </form>    
{% endblock content %}

myform/forms/templates/forms/entry.html
{% extends "base.html" %}
{% load bootstrap %}

{% block title %}エントリ{% endblock title %}


{% block content %}
    <h3 class="page-header">エントリ</h3>
    <form action="{% url 'forms:confirm' %}" method="post" class="form-horizontal" role="form">
        {% csrf_token %}
        {{ form|bootstrap_horizontal }}
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-primary">確認</button>
            </div>
        </div>
    </form>
{% endblock content %}